source 'https://rubygems.org'



gem 'rails', '~> 5.0.0', '>= 5.0.0.1'

gem 'bootstrap-sass', '3.3.6'

gem 'sqlite3'

gem 'puma', '~> 3.0'

gem 'sass-rails', '~> 5.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.2'

gem 'jquery-rails'

gem 'turbolinks', '~> 5'

gem 'jbuilder', '~> 2.5'

gem "jquery-slick-rails", '>= 1.6'

gem "twitter-bootstrap-rails"

gem 'geocoder'
gem 'gmaps4rails'

gem 'devise', '~> 4.1', '>= 4.1.1'

group :development, :test do

  gem 'byebug', platform: :mri
end

group :development do

  gem 'web-console'
  gem 'listen', '~> 3.0.5'

  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end


gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
